# -*- coding: utf-8 -*-
"""ProyectoQuantum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKvOWTjcPUcc_kh1E0OulZrcEXmSsMfn

# Generación de los elementos
"""

# -*- coding: utf-8 -*-
"""ProyectoEscuelaVerano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HiVeblQmlK5i01mk6yiTeGuOmx8EZRJH
"""

import pandas as pd
import random

# Fijar un número en un generador aleatorio.
random.seed(42)

# Opciones de visualización
pd.set_option('display.max_columns', None)   # muestra todas las columnas
pd.set_option('display.width', 1000)         # aumenta el ancho máximo
pd.set_option('display.max_rows', None)      # muestra todas las filas

# Definición de reglas de puntuación
algoritmos = {"RSA-2048":10, "ECC-P256":8, "AES-256":2, "SHA-256":5, "PQC":0}
criticidad = {"Alta":10, "Media":5, "Baja":2}
sensibilidad = {"Secreto":10, "Confidencial":7, "Interno":4, "Público":1}
retencion = {">20":10, "10-20":7, "5-10":4, "<5":1}
exposicion = {"Alta":10, "Media":5, "Baja":2}
migracion = {"Alta":10, "Media":5, "Baja":2}

#Variables descriptivas
tipos_activo = ["Certificado digital", "Clave de firma", "Clave de cifrado",
                "Credencial de VPN", "Token de autenticación"]
servicios = ["TLS", "VPN", "Firma digital", "Identidad", "Correo", "API interna"]
usos_criptograficos = ["Cifrado en tránsito", "Cifrado en reposo",
                       "Firma digital", "Autenticación"]
tamanos_clave = {  # tamaño típico asociado a cada algoritmo, no aleatorio
    "RSA-2048": "2048 bits", "ECC-P256": "256 bits",
    "AES-256": "256 bits", "SHA-256": "256 bits", "PQC": "Variable (NIST PQC)"
}
dependencias_proveedor = ["Alta", "Media", "Baja"]
vigencias = ["Vigente", "Próximo a expirar", "Expirado"]


# Generar dataset sintético
registros = []
for i in range(60):  # entre 40 y 60 registros
    activo = f"Activo_{i+1}" # Nombre del archivo
    alg = random.choice(list(algoritmos.keys()))
    crit = random.choice(list(criticidad.keys()))
    sens = random.choice(list(sensibilidad.keys()))
    ret = random.choice(list(retencion.keys()))
    exp = random.choice(list(exposicion.keys()))
    mig = random.choice(list(migracion.keys()))

    tipo_activo = random.choice(tipos_activo)
    servicio = random.choice(servicios)
    uso_cripto = random.choice(usos_criptograficos)
    tam_clave = tamanos_clave[alg]
    dep_proveedor = random.choice(dependencias_proveedor)
    vigencia = random.choice(vigencias)

    total = (algoritmos[alg] + criticidad[crit] + sensibilidad[sens] +
             retencion[ret] + exposicion[exp] + migracion[mig])

    registros.append([activo, tipo_activo, servicio, uso_cripto, alg, tam_clave, exp, crit, sens, ret, dep_proveedor, mig, vigencia, total])

# Crear DataFrame
df = pd.DataFrame(registros, columns=[
    "Identificador", "Tipo de activo", "Servicio", "Uso criptográfico",
    "Algoritmo", "Tamaño de clave", "Exposición", "Criticidad",
    "Sensibilidad", "Retención (años)", "Dependencia de proveedor",
    "Migración", "Vigencia", "Score Total"
])

print(df.head().to_string(index=False))
print(len(df))
print(df.to_string(index=False))

df.to_csv("inventario_sintetico.csv", index=False)

"""# Validación"""

# -*- coding: utf-8 -*-
"""
validacion.py — Módulo de validación del inventario criptográfico (CryptoRisk AI)

Responsabilidad única: recibir el CSV cargado por el usuario en Streamlit,
validar columnas, tipos y dominios, y devolver un DataFrame limpio más un
reporte de filas rechazadas. No calcula riesgo ni ejecuta clustering — eso
vive en reglas.py y clustering.py, tal como pide la sección 6 del
anteproyecto ("módulos de validación, reglas, clustering, recomendaciones
y presentación").
"""

import pandas as pd

# Columnas obligatorias según el diccionario de la sección 5 del anteproyecto
COLUMNAS_ESPERADAS = [
    "Identificador", "Tipo de activo", "Servicio", "Uso criptográfico",
    "Algoritmo", "Tamaño de clave", "Exposición", "Criticidad",
    "Sensibilidad", "Retención (años)", "Dependencia de proveedor",
    "Migración", "Vigencia"
]

# Dominios válidos por columna (deben coincidir con reglas.py)
DOMINIOS_VALIDOS = {
    "Algoritmo": {"RSA-2048", "ECC-P256", "AES-256", "SHA-256", "PQC"},
    "Criticidad": {"Alta", "Media", "Baja"},
    "Sensibilidad": {"Secreto", "Confidencial", "Interno", "Público"},
    "Retención (años)": {">20", "10-20", "5-10", "<5"},
    "Exposición": {"Alta", "Media", "Baja"},
    "Migración": {"Alta", "Media", "Baja"},
    "Dependencia de proveedor": {"Alta", "Media", "Baja"},
    "Vigencia": {"Vigente", "Próximo a expirar", "Expirado"},
}


class ResultadoValidacion:
    """Contenedor simple para el resultado de la validación."""
    def __init__(self, df_valido, df_rechazados, errores):
        self.df_valido = df_valido
        self.df_rechazados = df_rechazados
        self.errores = errores  # lista de strings con el detalle de cada rechazo

    @property
    def es_valido(self):
        """True si hay al menos un registro válido y no faltan columnas."""
        return self.df_valido is not None and len(self.df_valido) > 0


def validar_columnas(df: pd.DataFrame):
    """Verifica que estén todas las columnas obligatorias.

    Devuelve una lista de columnas faltantes (vacía si todo está bien).
    """
    return [col for col in COLUMNAS_ESPERADAS if col not in df.columns]


def validar_dominios(df: pd.DataFrame):
    """Revisa fila por fila que cada valor esté dentro del dominio permitido.

    Devuelve (df_valido, df_rechazados, lista_de_errores).
    """
    errores = []
    filas_validas = []
    filas_rechazadas = []

    for idx, fila in df.iterrows():
        motivo = None

        # Nulos en cualquier columna obligatoria
        if fila[COLUMNAS_ESPERADAS].isnull().any():
            motivo = "contiene valores vacíos en columnas obligatorias"

        # Dominios inválidos
        if motivo is None:
            for col, valores_validos in DOMINIOS_VALIDOS.items():
                if fila[col] not in valores_validos:
                    motivo = f"valor no permitido en '{col}': {fila[col]!r}"
                    break

        if motivo is None:
            filas_validas.append(idx)
        else:
            filas_rechazadas.append(idx)
            errores.append(f"Fila {idx} ({fila.get('Identificador', '?')}): {motivo}")

    df_valido = df.loc[filas_validas].reset_index(drop=True)
    df_rechazados = df.loc[filas_rechazadas].reset_index(drop=True)
    return df_valido, df_rechazados, errores


def validar_duplicados(df: pd.DataFrame):
    """Detecta identificadores duplicados. Devuelve la lista de duplicados."""
    duplicados = df[df.duplicated(subset=["Identificador"], keep=False)]
    return duplicados


def validar_inventario(df: pd.DataFrame) -> ResultadoValidacion:
    """Punto de entrada único del módulo: valida columnas, dominios y duplicados.

    Uso típico desde Streamlit:
        resultado = validar_inventario(df_cargado)
        if not resultado.es_valido:
            st.error("El archivo no tiene registros válidos.")
        else:
            st.dataframe(resultado.df_valido)
    """
    faltantes = validar_columnas(df)
    if faltantes:
        errores = [f"Faltan columnas obligatorias: {', '.join(faltantes)}"]
        return ResultadoValidacion(None, df, errores)

    df_valido, df_rechazados, errores = validar_dominios(df)

    duplicados = validar_duplicados(df_valido)
    if len(duplicados) > 0:
        errores.append(
            f"Se encontraron {len(duplicados)} filas con Identificador duplicado; "
            "se conservó solo la primera aparición de cada una."
        )
        df_valido = df_valido.drop_duplicates(subset=["Identificador"], keep="first")

    return ResultadoValidacion(df_valido, df_rechazados, errores)


if __name__ == "__main__":
    # Prueba rápida con el CSV que ya generó el equipo
    df = pd.read_csv("inventario_sintetico.csv")
    resultado = validar_inventario(df)
    print(f"Registros válidos: {len(resultado.df_valido)}")
    print(f"Registros rechazados: {len(resultado.df_rechazados)}")
    for e in resultado.errores:
        print(" -", e)

"""# Reglas"""

import pandas as pd

# Mismas reglas de puntuación que en el generador del dataset.
# IMPORTANTE: si el equipo decide ajustar los pesos de 'algoritmos'
# (por ejemplo, acercar SHA-256 y AES-256), este es el único lugar
# donde hay que cambiarlo — no en el generador ni en Streamlit.
PESOS = {
    "Algoritmo": {"RSA-2048": 10, "ECC-P256": 8, "AES-256": 2, "SHA-256": 5, "PQC": 0},
    "Criticidad": {"Alta": 10, "Media": 5, "Baja": 2},
    "Sensibilidad": {"Secreto": 10, "Confidencial": 7, "Interno": 4, "Público": 1},
    "Retención (años)": {">20": 10, "10-20": 7, "5-10": 4, "<5": 1},
    "Exposición": {"Alta": 10, "Media": 5, "Baja": 2},
    "Migración": {"Alta": 10, "Media": 5, "Baja": 2},
}

# Puntaje máximo posible (10+10+10+10+10+10), usado para normalizar
# el score a un rango 0-100 y para definir los umbrales de nivel de riesgo.
SCORE_MAXIMO = sum(max(escala.values()) for escala in PESOS.values())


def calcular_subpuntajes(fila: pd.Series) -> dict:
    """Devuelve el puntaje individual de cada una de las 6 variables de riesgo.

    Útil para el clustering (que debe recibir el vector de subpuntajes,
    no solo el Score Total) y para que el dashboard explique el resultado
    variable por variable.
    """
    return {variable: PESOS[variable][fila[variable]] for variable in PESOS}


def calcular_score(fila: pd.Series) -> int:
    """Score total determinístico: suma de los 6 subpuntajes."""
    subpuntajes = calcular_subpuntajes(fila)
    return sum(subpuntajes.values())


def calcular_score_normalizado(fila: pd.Series) -> float:
    """Score en escala 0-100, más fácil de interpretar en el dashboard."""
    return round(100 * calcular_score(fila) / SCORE_MAXIMO, 1)


def clasificar_nivel_riesgo(score_normalizado: float) -> str:
    """Traduce el score normalizado (0-100) a un nivel de riesgo cualitativo,
    siguiendo el enfoque de escalas de NIST SP 800-30 (Muy Baja/Baja/
    Moderada/Alta/Muy Alta), simplificado a 3 niveles para el MVP.

    Los umbrales (33 / 66) son una decisión de diseño del equipo — deben
    documentarse en la ficha de datos y pueden ajustarse si, al ver la
    distribución real del dataset, no separan bien los grupos.
    """
    if score_normalizado >= 66:
        return "Alto"
    elif score_normalizado >= 33:
        return "Medio"
    else:
        return "Bajo"


def generar_recomendacion(nivel_riesgo: str) -> str:
    """Plantilla determinística de recomendación por nivel de riesgo.

    Nada de IA generativa (excluido explícitamente en la sección 7 del
    anteproyecto) — son plantillas fijas y trazables.
    """
    plantillas = {
        "Alto": (
            "Revisar este activo de forma prioritaria. Evaluar tiempo de "
            "migración frente a los años de retención restantes (criterio "
            "de Mosca, 2018: X + Y > Z)."
        ),
        "Medio": (
            "Incluir en el plan de migración a mediano plazo; monitorear "
            "cambios en criticidad o exposición."
        ),
        "Bajo": (
            "Sin acción inmediata; reevaluar en el próximo ciclo de "
            "inventario criptográfico."
        ),
    }
    return plantillas[nivel_riesgo]


def aplicar_reglas(df: pd.DataFrame) -> pd.DataFrame:
    """Punto de entrada único del módulo: recibe el DataFrame ya validado
    (ver validacion.py) y devuelve una copia enriquecida con:
    Score Total, Score Normalizado, Nivel de Riesgo y Recomendación.
    """
    df = df.copy()
    df["Score Total"] = df.apply(calcular_score, axis=1)
    df["Score Normalizado"] = df.apply(calcular_score_normalizado, axis=1)
    df["Nivel de Riesgo"] = df["Score Normalizado"].apply(clasificar_nivel_riesgo)
    df["Recomendación"] = df["Nivel de Riesgo"].apply(generar_recomendacion)
    return df

# Content of the 'reglas' module to be written to a file for import.
reglas_module_content = ''


if __name__ == "__main__":
    # The content of reglas.py needs to be written to a file for import in other cells.
    with open("reglas.py", "w") as f:
        f.write(reglas_module_content)

    # The content of validacion.py is defined in cell jiECejJSkF2f. To allow
    # importing it as a module, we first write its content to a file.
    validacion_code = ''

    with open("validacion.py", "w") as f:
        f.write(validacion_code)

    df = pd.read_csv("inventario_sintetico.csv")
    resultado = validar_inventario(df)
    df_enriquecido = aplicar_reglas(resultado.df_valido)
    print(df_enriquecido[["Identificador", "Score Total", "Score Normalizado",
                           "Nivel de Riesgo", "Recomendación"]].head(10))
    print(df_enriquecido["Nivel de Riesgo"].value_counts())

"""# Clustering"""

# -*- coding: utf-8 -*-
"""
clustering.py — Agrupamiento no supervisado (CryptoRisk AI)

Aplica K-Means sobre los subpuntajes de riesgo (no sobre el Score Total).
Evalúa k=2, 3 y 4 con semilla fija y reporta Silhouette Score.
Los clústeres describen perfiles similares; no sustituyen el Nivel de Riesgo
definido por las reglas (sección 6 del anteproyecto).
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Columnas de subpuntaje que se usarán para el clustering
# (deben coincidir con las claves de PESOS en reglas.py)
COLUMNAS_CLUSTER = [
    "Algoritmo", "Criticidad", "Sensibilidad",
    "Retención (años)", "Exposición", "Migración"
]

def preparar_matriz(df: pd.DataFrame, pesos: dict) -> np.ndarray:
    """Convierte las variables categóricas a sus subpuntajes numéricos
    y las estandariza. Devuelve la matriz lista para K-Means.
    """
    matriz = []
    for _, fila in df.iterrows():
        vector = [pesos[col][fila[col]] for col in COLUMNAS_CLUSTER]
        matriz.append(vector)
    matriz = np.array(matriz)
    scaler = StandardScaler()
    return scaler.fit_transform(matriz)

def evaluar_kmeans(matriz: np.ndarray, k_min: int = 2, k_max: int = 4, semilla: int = 42):
    """Prueba varios valores de k y devuelve el mejor según Silhouette Score
    junto con el modelo entrenado y la tabla de resultados.
    """
    resultados = []
    mejor_score = -1
    mejor_modelo = None
    mejor_k = None
    mejores_etiquetas = None

    for k in range(k_min, k_max + 1):
        modelo = KMeans(n_clusters=k, random_state=semilla, n_init=10)
        etiquetas = modelo.fit_predict(matriz)
        score = silhouette_score(matriz, etiquetas)
        resultados.append({"k": k, "silhouette": round(score, 4)})
        if score > mejor_score:
            mejor_score = score
            mejor_modelo = modelo
            mejor_k = k
            mejores_etiquetas = etiquetas

    tabla = pd.DataFrame(resultados)
    return mejor_k, mejor_modelo, mejores_etiquetas, mejor_score, tabla

def aplicar_clustering(df: pd.DataFrame, pesos: dict) -> pd.DataFrame:
    """Punto de entrada. Recibe el DataFrame ya enriquecido por reglas.py
    y añade la columna 'Cluster'.
    """
    df = df.copy()
    matriz = preparar_matriz(df, pesos)
    k, modelo, etiquetas, sil_score, tabla_k = evaluar_kmeans(matriz)

    df["Cluster"] = etiquetas
    # Información útil para el dashboard
    df.attrs["mejor_k"] = k
    df.attrs["silhouette"] = sil_score
    df.attrs["tabla_k"] = tabla_k

    return df

# Flujo completo de prueba
df = pd.read_csv("inventario_sintetico.csv")
resultado = validar_inventario(df)

if not resultado.es_valido:
    print("No hay registros válidos")
else:
    df_enriquecido = aplicar_reglas(resultado.df_valido)
    df_final = aplicar_clustering(df_enriquecido, PESOS)

    print("=== Resumen ===")
    print(f"Mejor k: {df_final.attrs['mejor_k']}")
    print(f"Silhouette Score: {df_final.attrs['silhouette']}")
    print("\nDistribución por Nivel de Riesgo:")
    print(df_final["Nivel de Riesgo"].value_counts())
    print("\nDistribución por Cluster:")
    print(df_final["Cluster"].value_counts())
    print("\nMuestra de resultados:")
    print(df_final[["Identificador", "Score Total", "Nivel de Riesgo", "Cluster"]].head(15))

# Perfil de cada cluster (medias de los subpuntajes)
for col in ["Algoritmo", "Criticidad", "Sensibilidad", "Retención (años)", "Exposición", "Migración"]:
    df_final[col + "_score"] = df_final.apply(lambda r: PESOS[col][r[col]], axis=1)

perfil = df_final.groupby("Cluster")[[c + "_score" for c in ["Algoritmo", "Criticidad", "Sensibilidad", "Retención (años)", "Exposición", "Migración"]]].mean().round(1)
print(perfil)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# # app.py — CryptoRisk AI Dashboard
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import silhouette_score
# 
# st.set_page_config(page_title="CryptoRisk AI", layout="wide")
# st.title("CryptoRisk AI — Priorización de activos criptográficos")
# 
# # -------------------- PESOS Y FUNCIONES (idénticos al notebook) --------------------
# PESOS = {
#     "Algoritmo": {"RSA-2048": 10, "ECC-P256": 8, "AES-256": 2, "SHA-256": 5, "PQC": 0},
#     "Criticidad": {"Alta": 10, "Media": 5, "Baja": 2},
#     "Sensibilidad": {"Secreto": 10, "Confidencial": 7, "Interno": 4, "Público": 1},
#     "Retención (años)": {">20": 10, "10-20": 7, "5-10": 4, "<5": 1},
#     "Exposición": {"Alta": 10, "Media": 5, "Baja": 2},
#     "Migración": {"Alta": 10, "Media": 5, "Baja": 2},
# }
# SCORE_MAXIMO = sum(max(v.values()) for v in PESOS.values())
# 
# COLUMNAS_ESPERADAS = [
#     "Identificador", "Tipo de activo", "Servicio", "Uso criptográfico",
#     "Algoritmo", "Tamaño de clave", "Exposición", "Criticidad",
#     "Sensibilidad", "Retención (años)", "Dependencia de proveedor",
#     "Migración", "Vigencia"
# ]
# 
# DOMINIOS_VALIDOS = {
#     "Algoritmo": {"RSA-2048", "ECC-P256", "AES-256", "SHA-256", "PQC"},
#     "Criticidad": {"Alta", "Media", "Baja"},
#     "Sensibilidad": {"Secreto", "Confidencial", "Interno", "Público"},
#     "Retención (años)": {">20", "10-20", "5-10", "<5"},
#     "Exposición": {"Alta", "Media", "Baja"},
#     "Migración": {"Alta", "Media", "Baja"},
#     "Dependencia de proveedor": {"Alta", "Media", "Baja"},
#     "Vigencia": {"Vigente", "Próximo a expirar", "Expirado"},
# }
# 
# def validar_inventario(df):
#     faltantes = [c for c in COLUMNAS_ESPERADAS if c not in df.columns]
#     if faltantes:
#         return None, [f"Faltan columnas: {', '.join(faltantes)}"]
#     errores = []
#     validos = []
#     for idx, fila in df.iterrows():
#         motivo = None
#         if fila[COLUMNAS_ESPERADAS].isnull().any():
#             motivo = "valores vacíos"
#         if motivo is None:
#             for col, vals in DOMINIOS_VALIDOS.items():
#                 if fila[col] not in vals:
#                     motivo = f"valor inválido en {col}"
#                     break
#         if motivo is None:
#             validos.append(idx)
#         else:
#             errores.append(f"Fila {idx}: {motivo}")
#     return df.loc[validos].reset_index(drop=True), errores
# 
# def aplicar_reglas(df):
#     df = df.copy()
#     def score(fila):
#         return sum(PESOS[v][fila[v]] for v in PESOS)
#     df["Score Total"] = df.apply(score, axis=1)
#     df["Score Normalizado"] = (df["Score Total"] / SCORE_MAXIMO * 100).round(1)
#     df["Nivel de Riesgo"] = df["Score Normalizado"].apply(
#         lambda x: "Alto" if x >= 66 else ("Medio" if x >= 33 else "Bajo")
#     )
#     plantillas = {
#         "Alto": "Revisar prioritariamente. Evaluar tiempo de migración vs. retención (Mosca).",
#         "Medio": "Incluir en plan de migración a mediano plazo.",
#         "Bajo": "Sin acción inmediata. Reevaluar en próximo ciclo."
#     }
#     df["Recomendación"] = df["Nivel de Riesgo"].map(plantillas)
#     return df
# 
# def aplicar_clustering(df):
#     cols = list(PESOS.keys())
#     matriz = np.array([[PESOS[c][fila[c]] for c in cols] for _, fila in df.iterrows()])
#     matriz = StandardScaler().fit_transform(matriz)
#     mejor_k, mejor_score, mejor_etiquetas = 2, -1, None
#     for k in range(2, 5):
#         modelo = KMeans(n_clusters=k, random_state=42, n_init=10)
#         etiquetas = modelo.fit_predict(matriz)
#         sil = silhouette_score(matriz, etiquetas)
#         if sil > mejor_score:
#             mejor_k, mejor_score, mejor_etiquetas = k, sil, etiquetas
#     df = df.copy()
#     df["Cluster"] = mejor_etiquetas
#     df.attrs["mejor_k"] = mejor_k
#     df.attrs["silhouette"] = round(mejor_score, 3)
#     return df
# 
# # -------------------- INTERFAZ --------------------
# st.sidebar.header("Carga de inventario")
# archivo = st.sidebar.file_uploader("Sube el CSV del inventario", type=["csv"])
# 
# if archivo is not None:
#     df_raw = pd.read_csv(archivo)
#     df_valido, errores = validar_inventario(df_raw)
# 
#     if df_valido is None or len(df_valido) == 0:
#         st.error("No hay registros válidos.")
#         if errores:
#             st.write(errores)
#     else:
#         df = aplicar_reglas(df_valido)
#         df = aplicar_clustering(df)
# 
#         # Métricas principales
#         col1, col2, col3, col4 = st.columns(4)
#         col1.metric("Registros válidos", len(df))
#         col2.metric("Mejor k", df.attrs["mejor_k"])
#         col3.metric("Silhouette", df.attrs["silhouette"])
#         col4.metric("Activos Alto riesgo", (df["Nivel de Riesgo"] == "Alto").sum())
# 
#         # Ranking prioritario
#         st.subheader("Ranking prioritario (Top 10)")
#         ranking = df.sort_values("Score Total", ascending=False).head()
#         st.dataframe(
#             ranking[["Identificador", "Algoritmo", "Criticidad", "Exposición",
#                      "Score Total", "Nivel de Riesgo", "Cluster", "Recomendación"]],
#             use_container_width=True, hide_index=True
#         )
# 
#         # Distribuciones
#         c1, c2 = st.columns(2)
#         with c1:
#             st.subheader("Distribución por Nivel de Riesgo")
#             st.bar_chart(df["Nivel de Riesgo"].value_counts())
#         with c2:
#             st.subheader("Distribución por Cluster")
#             st.bar_chart(df["Cluster"].value_counts())
# 
#         # Perfiles de clúster
#         st.subheader("Perfiles de los clústeres")
#         st.markdown("""
#         - **Cluster 0 – Exposición residual**: algoritmos de menor riesgo cuántico, pero alta exposición.
#         - **Cluster 1 – Migración diferida**: algoritmos clásicos en contextos de baja criticidad/exposición.
#         - **Cluster 2 – Prioridad crítica**: algoritmos vulnerables + alta criticidad + alta exposición + larga retención.
#         """)
# 
#         # Tabla completa
#         with st.expander("Ver inventario completo enriquecido"):
#             st.dataframe(df, use_container_width=True)
# 
#         # Descarga
#         csv = df.to_csv(index=False).encode("utf-8")
#         st.download_button("Descargar resultados (CSV)", csv, "cryptorisk_resultados.csv", "text/csv")
# 
# else:
#     st.info("Sube el archivo `inventario_sintetico.csv` para comenzar.")